### ISSUE TITLE
Update bitcoinjs-lib to latest version (v6.1.0)

### ISSUE THREAD

**Issue by yknl** [secretkeylabs/xverse-core#140]
The current version of bitcoinjs-lib we're using is incompatible with the Ledger integration.

@scure/btc-signer doesn't seem to work with Ledger at all

We are using part of bitcoinjs-lib for certain wallet functions. Upgrading the package will break these, so we need to reimplement using a different library.

**Comment by paulmillr** [comment]
>@scure/btc-signer doesn't seem to work with Ledger at all

Do you know why?

**Comment by m-aboelenein** [comment]
> > @scure/btc-signer doesn't seem to work with Ledger at all
> 
> Do you know why?

Hey @paulmillr thanks for reaching out our experience with using`@scure/btc-signer` for ledger was cut short because ledger was failing to sign the transaction passed to it  throwing a generic error so we couldn't identify what the problem was.

we are more than happy to investigate this further with you as we would love to be using `@scure/btc-signer` for both the hot wallet and ledger

**Comment by paulmillr** [comment]
Sure thing.

If you could create any reproducible code, that would help. We could identify and investigate the cause.
