### ISSUE TITLE
sigHash error

### ISSUE THREAD

**Issue by devlancer412** [secretkeylabs/xverse-core#381]
I got this error when signing PSBT.

![image](https://github.com/secretkeylabs/xverse-core/assets/101313445/e0bc1787-d1a8-49a0-8fbd-7058155771a3)

What's the reason of this error?

sigHash: bitcoin.Transaction.SIGHASH_SINGLE | bitcoin.Transaction.SIGHASH_ANYONECANPAY = 3 | 128 = 131

What's wrong with my psbt?

**Comment by LightRider5** [comment]
I have the same issue. It seems Xverse wallet can sign only transactions with sigHash = 131 (SINGLE_ANYONECANPAY).

Here I create the input: 

```
let input = {
        txid: paymentOutput.txid,
        index: paymentOutput.vout,
        redeemScript,
        sequence: 0xfffffffd, // enables RBF
        sighashType: btc.SigHash.ALL
    };
```


And here I try to sign the transaction: 

```
signTransaction({
            payload: {
                network: {
                    type: networkType
                },
                message: 'Sign Transaction',
                psbtBase64,
                broadcast: true,
                inputsToSign: [
                    {
                        address: paymentAddress,
                        signingIndexes: [0],
                        sigHash: btc.SigHash.ALL
                    },
                ],
            },
            onFinish: (response) => {

                const txId = response.txId || '';

                observer.next({ txId });
                observer.complete();
            },
            onCancel: () => {
                observer.error(new Error('Request was cancelled'));
            }
        });
```

In the above example I want to sign all inputs and outputs but Xverse shows me

`Input with not allowed sigHash=1. Allowed: 131`

The problem is that if you can only sign transactions with sigHash = 131 and you sign a transaction with more than one output an attacker can change the outputs and steal your money.

This already happened to me in this transactions: https://mempool.space/tx/446377ecee7620297bd2367dc81659546776eff22fc139810abeaf2f4146193f 

The attacker replaced the fee output and the change output for his advantage.

It would be good if Xverse also gives you a warning when you sign such a transaction.

**Comment by victorkirov** [comment]
Hi guys

Sorry for the late reply. We mainly monitor sats-connect repo for external issues and didn't notice these.

I just tried to reproduce this issue and didn't manage, it quite happily signed a SigHash ALL. Could you please provide a full code snippet of the txn generation and the call to sats connect that fails in a reproducable way with the above issue? 🙏

**Comment by LightRider5** [comment]
Hi,

thank you. I just managed to get the wallet to sign with SigHash ALL successfully. The problem was actually elsewhere in the code, so Xverse did fine. However, it would still be nice to have a notification when a user signs a transaction with SigHash SINGLE and there's more than one output.

**Comment by victorkirov** [comment]
That's a really good idea. I'll notify our product team to add it to the backlog for one of the close releases 🙌
